spring.application.name=imei
#zona horaria
spring.jpa.properties.hibernate.jdbc.time_zone=America/Mexico_City
#configuracion conexion a bd
#funciona en local
spring.datasource.url=jdbc:postgresql://localhost:5432/centroimei
#funciona en Docker
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/centroimei
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
#configuraciones mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rafaelcortesp.17@gmail.com
spring.mail.password=rbcxoiwrxkkbnjwp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
#propiedades del webhook
payments.webhook.secret=mi_clave_secreta_de_prueba_123
#server.forward-headers-strategy=framework
#url de tunnel
cors.allowed-origins=http://localhost:4200,http://192.168.1.83:4200
#url para registrar token en bd
imei.registration.token=http://192.168.1.83:4200/complete-registration?token=