spring.application.name=imei
#funciona en local
#spring.datasource.url=jdbc:postgresql://localhost:5432/centroimei
#funciona en Docker
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/centroimei
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true